## AS 65002 pod2 leaf4 (Juniper JunOS, set format)
set system host-name leaf4
set interfaces lo0 unit 0 family inet address 10.255.2.12/32
set interfaces ge-0/0/0 description to-spine3
set interfaces ge-0/0/0 unit 0 family inet address 10.2.2.2/30
set interfaces ge-0/0/1 description to-spine4
set interfaces ge-0/0/1 unit 0 family inet address 10.2.4.2/30
set interfaces ge-0/0/2 description server-lan
set interfaces ge-0/0/2 unit 0 family inet address 192.168.14.1/24
set routing-options autonomous-system 65002
set protocols bgp group ibgp type internal
set protocols bgp group ibgp neighbor 10.2.2.1 peer-as 65002
set protocols bgp group ibgp neighbor 10.2.4.1 peer-as 65002
