## AS 65001 pod1 spine2 (Juniper JunOS, set format)
set system host-name spine2
set interfaces lo0 unit 0 family inet address 10.255.1.2/32
set interfaces ge-0/0/0 description to-core2
set interfaces ge-0/0/0 unit 0 family inet address 10.0.3.2/30
set interfaces ge-0/0/1 description to-leaf1
set interfaces ge-0/0/1 unit 0 family inet address 10.1.3.1/30
set interfaces ge-0/0/2 description to-leaf2
set interfaces ge-0/0/2 unit 0 family inet address 10.1.4.1/30
set routing-options autonomous-system 65001
set protocols bgp group ext type external
set protocols bgp group ext neighbor 10.0.3.1 peer-as 65000
set protocols bgp group ibgp type internal
set protocols bgp group ibgp neighbor 10.1.3.2 peer-as 65001
set protocols bgp group ibgp neighbor 10.1.4.2 peer-as 65001
