## Juniper JunOS configuration in `set` format (VRF demo: R2)
set system host-name R2
set interfaces ge-0/0/0 description to-R1-global
set interfaces ge-0/0/0 unit 0 family inet address 10.0.12.2/24
set interfaces ge-0/0/1 description CUST-BLUE-link
set interfaces ge-0/0/1 unit 0 family inet address 10.6.6.2/24
set interfaces lo0 unit 0 family inet address 2.2.2.2/32
set routing-options autonomous-system 65002
set protocols bgp group ext type external
set protocols bgp group ext neighbor 10.0.12.1 peer-as 65020
set routing-instances BLUE interface ge-0/0/1.0
set routing-instances BLUE routing-options static route 192.168.60.0/24 next-hop 10.6.6.1
set routing-instances BLUE protocols bgp group v neighbor 10.6.6.1 peer-as 65020
