set system host-name edge-rtr-jun
set interfaces lo0 unit 0 family inet address 10.10.0.4/32
set interfaces ge-0/0/0 unit 0 description edge-to-core01
set interfaces ge-0/0/0 unit 0 family inet address 10.10.14.2/30
set interfaces ge-0/0/1 unit 0 description edge-to-isp
set interfaces ge-0/0/1 unit 0 family inet address 203.0.113.2/30
set protocols ospf area 0.0.0.2 nssa
set protocols ospf area 0.0.0.2 interface lo0.0 passive
set protocols ospf area 0.0.0.2 interface ge-0/0/0.0 metric 20
set routing-options autonomous-system 65010
set routing-options router-id 10.10.0.4
set protocols bgp group RR type internal
set protocols bgp group RR local-address 10.10.0.4
set protocols bgp group RR cluster 10.10.0.1
set protocols bgp group RR peer-as 65010
set protocols bgp group RR neighbor 10.10.0.1
set protocols bgp group EXT type external
set protocols bgp group EXT peer-as 65020
set protocols bgp group EXT neighbor 203.0.113.1
