## Juniper JunOS set-format running-config - R3 (area 1 stub member; mismatch link to R4)
set system host-name R3
set interfaces lo0 unit 0 family inet address 3.3.3.3/32
set interfaces ge-0/0/0 unit 0 description AREA1-P2P-to-R1
set interfaces ge-0/0/0 unit 0 family inet address 10.0.13.3/24
set interfaces ge-0/0/1 unit 0 description MISMATCH-LINK-to-R4
set interfaces ge-0/0/1 unit 0 family inet address 10.0.34.3/24
set routing-options router-id 3.3.3.3
set protocols ospf area 1 stub
set protocols ospf area 1 interface lo0.0 passive
set protocols ospf area 1 interface ge-0/0/0.0 metric 30
set protocols ospf area 1 interface ge-0/0/0.0 interface-type p2p
set protocols ospf area 1 interface ge-0/0/1.0 metric 40
