## Juniper JunOS set-format running-config - R4 (area 2 NSSA member; mismatch link to R3)
set system host-name R4
set interfaces lo0 unit 0 family inet address 4.4.4.4/32
set interfaces ge-0/0/0 unit 0 description AREA2-P2P-to-R2
set interfaces ge-0/0/0 unit 0 family inet address 10.0.24.4/24
set interfaces ge-0/0/1 unit 0 description MISMATCH-LINK-to-R3
set interfaces ge-0/0/1 unit 0 family inet address 10.0.34.4/24
set routing-options router-id 4.4.4.4
set protocols ospf area 2 nssa
set protocols ospf area 2 interface lo0.0 passive
set protocols ospf area 2 interface ge-0/0/0.0 metric 20
set protocols ospf area 2 interface ge-0/0/0.0 interface-type p2p
set protocols ospf area 3 interface ge-0/0/1.0 metric 40
