## Juniper JunOS set-format config - R2 (iBGP client, AS 65001)
##
## R2 peers ONLY with the hub R1 (group internal, local-address = loopback).
## It does not peer R3 or R4 -> contributes to the incomplete iBGP mesh.
##
set system host-name R2
set interfaces lo0 unit 0 family inet address 10.255.0.2/32
set interfaces ge-0/0/0 unit 0 description P2P-to-R1
set interfaces ge-0/0/0 unit 0 family inet address 10.0.12.2/24
set routing-options autonomous-system 65001
set routing-options router-id 10.255.0.2
set protocols ospf area 0 interface lo0.0
set protocols ospf area 0 interface ge-0/0/0.0
set protocols bgp group internal type internal
set protocols bgp group internal neighbor 10.255.0.1 local-address 10.255.0.2
set protocols bgp group internal neighbor 10.255.0.1 peer-as 65001
