## Juniper JunOS configuration in set format - R4 (access, JunOS, iBGP)
set system host-name R4
set interfaces lo0 unit 0 family inet address 4.4.4.4/32
set interfaces ge-0/0/0 description SEG-to-R1-R3 10.0.100.0/24
set interfaces ge-0/0/0 unit 0 family inet address 10.0.100.4/24
set routing-options autonomous-system 65001
set routing-options router-id 4.4.4.4
set protocols ospf area 0 interface lo0.0
set protocols ospf area 0 interface ge-0/0/0.0
set protocols bgp group ibgp type internal
set protocols bgp group ibgp neighbor 2.2.2.2 peer-as 65001
set protocols bgp group ibgp neighbor 2.2.2.2 local-address 4.4.4.4
