## Juniper JunOS configuration in `set` format (sample) - OSPF interface all demo
set system host-name EDGE-JUNOS
set interfaces ge-0/0/0 description to-CORE-IOS
set interfaces ge-0/0/0 unit 0 family inet address 10.0.0.2/30
set interfaces ge-0/0/1 description LAN-B
set interfaces ge-0/0/1 unit 0 family inet address 192.168.20.1/24
set interfaces ge-0/0/2 description LAN-C
set interfaces ge-0/0/2 unit 0 family inet address 172.16.30.1/24
set interfaces lo0 unit 0 family inet address 10.255.0.2/32
set routing-options autonomous-system 65536
set protocols ospf area 0 interface all
set protocols bgp group ext type external
set protocols bgp group ext neighbor 10.0.0.1 peer-as 65536
